### ISSUE TITLE
R-028: Simplified Docker development setup

### ISSUE THREAD

**Issue by nhlongnguyen** [nhlongnguyen/mindbridge#51]
## Description
Implement a streamlined Docker Compose setup optimized for localhost development. This configuration focuses on simplicity and ease of use, providing only the essential services needed for the two core functionalities: GitHub repository analysis and documentation RAG search.

### Scenario 1: Quick Development Environment Setup
**As a developer**, I want to start the entire development environment with a single command so that I can quickly begin working on the application without complex setup procedures.

*Example*: I run `docker-compose up` and get:
- Neo4j database running on localhost:7474 (web interface) and :7687 (bolt protocol)
- All required volumes and networks configured
- Database initialized with proper indexes and constraints  
- Ready to accept connections from the FastAPI application
- Clear logs showing successful startup and health status

### Scenario 2: Development Database Management
**As a developer**, I want easy access to the Neo4j database for debugging and development so that I can inspect stored data, run queries, and troubleshoot issues.

*Example*: During development I can:
- Access Neo4j Browser at http://localhost:7474 for visual query interface
- Run Cypher queries to inspect stored code structure and documentation
- View graph relationships and vector embeddings
- Reset/clear database when needed for testing
- Export/import data for development scenarios

### Scenario 3: Persistent Development Data
**As a developer**, I want my development data to persist across container restarts so that I don't lose analyzed repositories and documentation when restarting services.

*Example*: When I restart Docker containers:
- Previously analyzed GitHub repositories remain in the database
- Stored documentation embeddings are preserved  
- Neo4j data survives container lifecycle
- Configuration and indexes are maintained
- Development work continues without data loss

### Docker Compose Configuration
- [ ] Single docker-compose.yml file for all development services
- [ ] Neo4j service configured with appropriate memory and storage settings
- [ ] Proper port mappings for development access (7474, 7687)
- [ ] Volume mounts for data persistence
- [ ] Environment variables for configuration

### Neo4j Setup & Configuration
- [ ] Neo4j Community Edition (sufficient for localhost development)
- [ ] APOC plugins enabled for advanced graph operations
- [ ] Vector search capabilities configured
- [ ] Development-friendly authentication (simple or disabled for localhost)
- [ ] Proper memory allocation for development workloads

### Data Persistence & Management
- [ ] Persistent volumes for Neo4j data
- [ ] Easy database reset/cleanup procedures
- [ ] Configuration file mounting for custom settings
- [ ] Backup and restore capabilities for development data
- [ ] Clear documentation for data management operations

### Development Experience
- [ ] Fast startup times (< 30 seconds for all services)
- [ ] Clear health checks and status reporting
- [ ] Comprehensive logging for troubleshooting
- [ ] Easy service restart and management
- [ ] Integration with existing development workflow

### Documentation & Usage
- [ ] Clear README instructions for setup and usage
- [ ] Common operations documented (start, stop, reset, backup)
- [ ] Troubleshooting guide for common issues
- [ ] Development best practices and tips
- [ ] Integration examples with FastAPI application

### Docker Compose Configuration
```yaml
# docker-compose.dev.yml
version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: mindbridge-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - ./neo4j/init:/docker-entrypoint-initdb.d
    environment:
      - NEO4J_AUTH=neo4j/mindbridge-dev
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=256m
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p mindbridge-dev 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:

networks:
  default:
    name: mindbridge-dev
```

### Neo4j Initialization Scripts
```cypher
// neo4j/init/001-create-constraints.cypher
// Create unique constraints
CREATE CONSTRAINT module_name_unique IF NOT EXISTS 
FOR (m:Module) REQUIRE m.full_name IS UNIQUE;

CREATE CONSTRAINT class_signature_unique IF NOT EXISTS 
FOR (c:Class) REQUIRE c.signature IS UNIQUE;

CREATE CONSTRAINT function_signature_unique IF NOT EXISTS 
FOR (f:Function) REQUIRE f.signature IS UNIQUE;

// Create property indexes
CREATE INDEX module_name_index IF NOT EXISTS FOR (m:Module) ON m.name;
CREATE INDEX class_name_index IF NOT EXISTS FOR (c:Class) ON c.name;
CREATE INDEX function_name_index IF NOT EXISTS FOR (f:Function) ON f.name;
CREATE INDEX doc_title_index IF NOT EXISTS FOR (d:Documentation) ON d.title;

// Create vector indexes for embeddings
CALL db.index.vector.createNodeIndex(
  'documentation_embeddings',
  'Documentation', 
  'embedding',
  1536,
  'cosine'
) YIELD name, labels, properties, state;
```

### Development Scripts
```bash
#\!/bin/bash
# scripts/dev-setup.sh

echo "🚀 Starting MindBridge development environment..."

# Start services
docker-compose -f docker-compose.dev.yml up -d

# Wait for Neo4j to be ready
echo "⏳ Waiting for Neo4j to start..."
until docker-compose -f docker-compose.dev.yml exec neo4j cypher-shell -u neo4j -p mindbridge-dev "RETURN 1" > /dev/null 2>&1; do
  sleep 2
done

echo "✅ Neo4j is ready\!"
echo "📊 Neo4j Browser: http://localhost:7474"
echo "🔌 Bolt connection: bolt://localhost:7687"
echo "🔑 Credentials: neo4j / mindbridge-dev"

# scripts/dev-reset.sh
#\!/bin/bash
echo "🗑️  Resetting development database..."
docker-compose -f docker-compose.dev.yml exec neo4j cypher-shell -u neo4j -p mindbridge-dev "MATCH (n) DETACH DELETE n"
echo "✅ Database reset complete"

# scripts/dev-status.sh  
#\!/bin/bash
echo "📊 Development Environment Status"
docker-compose -f docker-compose.dev.yml ps
echo ""
echo "🔍 Neo4j Health Check:"
docker-compose -f docker-compose.dev.yml exec neo4j cypher-shell -u neo4j -p mindbridge-dev "CALL dbms.components() YIELD name, versions, edition"
```

### Environment Variables
```bash
# .env.development
NEO4J_URI=bolt://localhost:7687
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=mindbridge-dev
NEO4J_DATABASE=neo4j

# FastAPI Configuration
ENVIRONMENT=development
LOG_LEVEL=DEBUG
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080

# Development Settings
DEBUG_MODE=true
ENABLE_DETAILED_LOGGING=true
```

### Health Check & Monitoring
```python
# healthcheck.py - Simple health check script
import asyncio
from neo4j import AsyncGraphDatabase
import aiohttp

async def check_neo4j_health():
    driver = AsyncGraphDatabase.driver(
        "bolt://localhost:7687",
        auth=("neo4j", "mindbridge-dev")
    )
    try:
        async with driver.session() as session:
            result = await session.run("RETURN 1 as health")
            record = await result.single()
            return record["health"] == 1
    finally:
        await driver.close()

async def main():
    neo4j_healthy = await check_neo4j_health()
    print(f"Neo4j: {'✅ Healthy' if neo4j_healthy else '❌ Unhealthy'}")

if __name__ == "__main__":
    asyncio.run(main())
```

## Dependencies
- **Enables**: R-025 (Neo4j database integration) - Provides database infrastructure
- **Supports**: All development work - Provides consistent development environment
- **Requires**: Docker and Docker Compose installed locally

## Priority & Complexity
- **Priority**: Medium - Important for development efficiency
- **Complexity**: Low-Medium - Docker configuration, service orchestration
- **Size**: Small-Medium (4-6 hours)
- **Phase**: Foundation Infrastructure
- **Estimated Days**: 0.5

## Success Metrics
- [ ] Complete environment starts in under 30 seconds
- [ ] Neo4j accessible and functional for development
- [ ] Data persists across container restarts
- [ ] Clear documentation enables easy onboarding
- [ ] Troubleshooting procedures resolve common issues
